# Generated by Django 2.2.9 on 2020-02-07 19:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGameUser',
            fields=[
                ('gamesuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('core.gamesuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invest_game.InvestmentGameUser')),
                ('reached_stage', models.CharField(choices=[('select_respondent', 'Reached respondent selection stage'), ('user_investment', 'Reached user investment stage'), ('respondent_investment', 'Reached respondent investment stage'), ('question1', 'Reached question 1 stage'), ('question2', 'Reached question 2 stage'), ('question3', 'Reached question 3 stage'), ('compare', 'Reached compare stage'), ('finish', 'Reached finish stage')], default='select_respondent', max_length=256)),
                ('respondent', models.CharField(choices=[('Ibrahim', 'Your respondent is Ibrahim'), ('Sahr', 'Your respondent is Sahr'), ('Sahal', 'Your respondent is Sahal'), ('Omar', 'Your respondent is Omar'), ('Eman', 'Your respondent is Eman'), ('Douglas', 'Your respondent is Douglas'), ('Christopher', 'Your respondent is Christopher'), ('Philip', 'Your respondent is Philip'), ('Theresa', 'Your respondent is Theresa'), ('Tracy', 'Your respondent is Tracy')], default=None, max_length=256, null=True)),
                ('user_investment', models.IntegerField(null=True)),
                ('respondent_investment_guess', models.IntegerField(null=True)),
                ('respondent_investment', models.IntegerField(null=True)),
                ('user_received', models.IntegerField(null=True)),
                ('user_bonus', models.IntegerField(default=0)),
                ('otherreturned', models.IntegerField(default=-1)),
                ('otherinvested', models.IntegerField(default=-1)),
                ('points', models.IntegerField(default=-1)),
                ('started_user_investment', models.DateTimeField(null=True)),
                ('finished_user_investment', models.DateTimeField(null=True)),
                ('started_respondent_investment', models.DateTimeField(null=True)),
                ('finished_respondent_investment', models.DateTimeField(null=True)),
                ('q1answer', models.CharField(max_length=255, null=True)),
                ('q2answer', models.CharField(max_length=255, null=True)),
                ('q3answer', models.CharField(max_length=255, null=True)),
                ('q4answer', models.CharField(max_length=255, null=True)),
                ('q5answer', models.CharField(max_length=255, null=True)),
                ('q6answer', models.CharField(max_length=255, null=True)),
                ('q7answer', models.CharField(max_length=255, null=True)),
                ('q8answer', models.CharField(max_length=255, null=True)),
                ('q9answer', models.CharField(max_length=255, null=True)),
                ('q10answer', models.CharField(max_length=255, null=True)),
                ('q11answer', models.CharField(max_length=255, null=True)),
                ('q12answer', models.CharField(max_length=255, null=True)),
                ('q13answer', models.CharField(max_length=255, null=True)),
                ('q14answer', models.CharField(max_length=255, null=True)),
                ('q15answer', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
