# Generated by Django 2.2.9 on 2020-02-05 19:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGameUser',
            fields=[
                ('gamesuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('core.gamesuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invest_game.InvestmentGameUser')),
                ('reached_stage', models.CharField(choices=[('select-respondent', 'Reached respondent selection stage'), ('user-investment', 'Reached user investment stage'), ('respondent-invenstment', 'Reached respondent investment stage'), ('comparison', 'Reached comparison stage'), ('thank-you', 'Reached thank you stage')], default=None, max_length=256, null=True)),
                ('invested', models.IntegerField(default=-1)),
                ('doneinvest', models.IntegerField(default=-1)),
                ('donereturn', models.IntegerField(default=-1)),
                ('respondent', models.TextField(blank=True, default=' ', null=True)),
                ('returned0', models.IntegerField(default=-1)),
                ('returned1', models.IntegerField(default=-1)),
                ('returned2', models.IntegerField(default=-1)),
                ('returned3', models.IntegerField(default=-1)),
                ('returned4', models.IntegerField(default=-1)),
                ('returned5', models.IntegerField(default=-1)),
                ('otherreturned', models.IntegerField(default=-1)),
                ('otherinvested', models.IntegerField(default=-1)),
                ('points', models.IntegerField(default=-1)),
                ('q1answer', models.CharField(default=' ', max_length=255)),
                ('q2answer', models.CharField(default=' ', max_length=255)),
                ('q3answer', models.CharField(default=' ', max_length=255)),
                ('q4answer', models.CharField(default=' ', max_length=255)),
                ('q5answer', models.CharField(default=' ', max_length=255)),
                ('q6answer', models.CharField(default=' ', max_length=255)),
                ('q7answer', models.CharField(default=' ', max_length=255)),
                ('q8answer', models.CharField(default=' ', max_length=255)),
                ('q9answer', models.CharField(default=' ', max_length=255)),
                ('q10answer', models.CharField(default=' ', max_length=255)),
                ('q11answer', models.CharField(default=' ', max_length=255)),
                ('q12answer', models.CharField(default=' ', max_length=255)),
                ('q13answer', models.CharField(default=' ', max_length=255)),
                ('q14answer', models.CharField(default=' ', max_length=255)),
                ('q15answer', models.CharField(default=' ', max_length=255)),
                ('q5type', models.IntegerField(default=-1)),
                ('startedinvested', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedinvested', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned0', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned0', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned1', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned1', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned2', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned2', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned3', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned3', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned4', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned4', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedreturned5', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedreturned5', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
