# Generated by Django 2.2.9 on 2020-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='news_source',
            field=models.CharField(help_text='Which do you think is your main source of news?', max_length=255, null=True),
        ),
    ]
