# Generated by Django 2.2.9 on 2020-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='respondent',
            field=models.CharField(blank=True, choices=[('Ibrahim', 'Ibrahim'), ('Sahr', 'Sahr'), ('Sahal', 'Sahal'), ('Omar', 'Omar'), ('Eman', 'Eman'), ('Douglas', 'Douglas'), ('Christopher', 'Christopher'), ('Philip', 'Philip'), ('Theresa', 'Theresa'), ('Tracy', 'Tracy')], max_length=256, null=True),
        ),
    ]
