# Generated by Django 2.2.9 on 2020-02-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user_investment',
            field=models.IntegerField(default=0),
        ),
    ]
