# Generated by Django 2.2.9 on 2020-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='q10answer',
            new_name='economic_outlook',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q11answer',
            new_name='general_trustworthiness',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q12answer',
            new_name='how_voted',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q13answer',
            new_name='islamic_extremism',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q14answer',
            new_name='multiple_agreement_question',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q15answer',
            new_name='multiple_agreement_question_type',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q1answer',
            new_name='muslim_coworkers',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q2answer',
            new_name='muslims_in_neighborhood',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q3answer',
            new_name='news_source',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q4answer',
            new_name='political_views',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q5answer',
            new_name='race_treated_unfairly',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q6answer',
            new_name='reducing_terrorism',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q7answer',
            new_name='religion_treated_unfairly',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q8answer',
            new_name='self_treated_unfairly',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='q9answer',
            new_name='us_citizen',
        ),
        migrations.AddField(
            model_name='investment',
            name='voted_last_election',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reached_stage',
            field=models.CharField(choices=[('select_respondent', 'Reached respondent selection stage'), ('user_investment', 'Reached user investment stage'), ('respondent_investment', 'Reached respondent investment stage'), ('question1', 'Reached question 1 stage'), ('question1_5', 'Reached question 1.5 stage'), ('question2', 'Reached question 2 stage'), ('question3', 'Reached question 3 stage'), ('compare', 'Reached compare stage'), ('finish', 'Reached finish stage')], default='select_respondent', max_length=256),
        ),
    ]
