# Generated by Django 2.2.9 on 2020-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0002_auto_20200206_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='respondent_investment_guess',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user_investment',
            field=models.IntegerField(null=True),
        ),
    ]
