# Generated by Django 2.2.9 on 2020-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0002_auto_20200219_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='started_question_1_5',
        ),
        migrations.AddField(
            model_name='investment',
            name='approve_of_trump',
            field=models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Do you approve or disapprove of the way Donald Trump is handling his job as president?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='started_question_2_5',
            field=models.DateTimeField(help_text='When the user landed on the question 2.5 stage (if relevant)', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='economic_outlook',
            field=models.CharField(choices=[('get_better', 'Get better'), ('stay_the_same', 'Stay the same'), ('get_worse', 'Get worse'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Over the next 12 months, do you expect the national economy to get better, get worse, or stay about the same?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='news_source',
            field=models.CharField(help_text='Where do you get most of your news?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='political_views',
            field=models.CharField(choices=[('democrats', 'The Democratic Party'), ('republicans', 'The Republican Party'), ('other', 'Other'), ('no_preference', 'No preference'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Are your political views generally closer to those of', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reached_stage',
            field=models.CharField(choices=[('select_respondent', 'User reached respondent selection stage'), ('user_investment', 'User reached user investment stage'), ('respondent_investment', 'User reached respondent investment stage'), ('question1', 'User reached question 1 stage'), ('question2', 'User reached question 2 stage'), ('question2_5', 'User reached question 2.5 stage'), ('question3', 'User reached question 3 stage'), ('compare', 'User reached compare stage'), ('finish', 'User reached finish stage')], default='select_respondent', max_length=256),
        ),
    ]
