# Generated by Django 2.2.9 on 2020-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0003_auto_20200329_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='reached_stage',
            field=models.CharField(choices=[('select_respondent', 'User reached respondent selection stage'), ('user_investment', 'User reached user investment stage'), ('respondent_investment', 'User reached respondent investment stage'), ('question1', 'User reached question 1 stage'), ('question2', 'User reached question 2 stage'), ('question2_5', 'User reached question 2.5 stage'), ('question3', 'User reached question 3 stage'), ('compare', 'User reached compare stage'), ('finish', 'User reached finish stage')], max_length=256, null=True),
        ),
    ]
