# Generated by Django 2.2.9 on 2020-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0004_auto_20200212_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user_bonus',
            field=models.IntegerField(choices=[(2, 'User received a bonus of $2'), (0, 'User received no bonus ($0)')], default=(None, 'Bonus not yet calculated'), null=True),
        ),
    ]
