# Generated by Django 2.2.9 on 2020-02-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0004_auto_20200206_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='q10answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q11answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q12answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q13answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q14answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q15answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q1answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q2answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q3answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q4answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q5answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q6answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q7answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q8answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='q9answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
