# Generated by Django 2.2.9 on 2020-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0004_auto_20200329_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='chinese_americans_ventilators',
            field=models.CharField(choices=[('no_ventilators', 'No ventilators'), ('low_preference_ventilators', 'Low preference for ventilators'), ('ventilators_if_available', 'Ventilators, if available'), ('high_preference_ventilators', 'High preference for ventilators'), ('always_ventilators', 'Always gets ventilators'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Ventilators for Chinese Americans', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='cooperate_treatment',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Covid-19 can only be beaten if countries cooperate in finding treatments and a vaccine.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='covid_bioweapon',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Covid-19 was a bioweapon designed by China to wage war on the United States.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='covid_blame',
            field=models.CharField(choices=[('chinese_government', 'The Chinese government'), ('united_states_government', 'The United States government'), ('equally_responsible', 'They are equally responsible'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Who is more to blame for the coronavirus pandemic in the United States?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='muslim_americans_ventilators',
            field=models.CharField(choices=[('no_ventilators', 'No ventilators'), ('low_preference_ventilators', 'Low preference for ventilators'), ('ventilators_if_available', 'Ventilators, if available'), ('high_preference_ventilators', 'High preference for ventilators'), ('always_ventilators', 'Always gets ventilators'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Ventilators for Muslim Americans', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='non_us_citizens_ventilators',
            field=models.CharField(choices=[('no_ventilators', 'No ventilators'), ('low_preference_ventilators', 'Low preference for ventilators'), ('ventilators_if_available', 'Ventilators, if available'), ('high_preference_ventilators', 'High preference for ventilators'), ('always_ventilators', 'Always gets ventilators'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Ventilators for non-U.S. citizens', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='over_65_ventilators',
            field=models.CharField(choices=[('no_ventilators', 'No ventilators'), ('low_preference_ventilators', 'Low preference for ventilators'), ('ventilators_if_available', 'Ventilators, if available'), ('high_preference_ventilators', 'High preference for ventilators'), ('always_ventilators', 'Always gets ventilators'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Ventilators for patients over 65', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='share_equipment',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Now that the U.S. has experienced shortages of medical equipment, we should share our masks, ventilators, and other lifesaving equipment with other countries after the virus subsides here.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='started_question_4',
            field=models.DateTimeField(help_text='When the user landed on the question 4 stage', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reached_stage',
            field=models.CharField(choices=[('select_respondent', 'User reached respondent selection stage'), ('user_investment', 'User reached user investment stage'), ('respondent_investment', 'User reached respondent investment stage'), ('question1', 'User reached question 1 stage'), ('question2', 'User reached question 2 stage'), ('question2_5', 'User reached question 2.5 stage'), ('question3', 'User reached question 3 stage'), ('question4', 'User reached question 4 stage'), ('compare', 'User reached compare stage'), ('finish', 'User reached finish stage')], max_length=256, null=True),
        ),
    ]
