# Generated by Django 2.2.9 on 2020-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0005_auto_20200206_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='q5type',
        ),
        migrations.AlterField(
            model_name='investment',
            name='reached_stage',
            field=models.CharField(choices=[('select_respondent', 'Reached respondent selection stage'), ('user_investment', 'Reached user investment stage'), ('respondent_investment', 'Reached respondent investment stage'), ('question1', 'Reached question 1 stage'), ('question2', 'Reached question 2 stage'), ('question3', 'Reached question 3 stage'), ('compare', 'Reached compare stage'), ('finish', 'Reached finish stage')], default='select_respondent', max_length=256),
        ),
    ]
