# Generated by Django 2.2.9 on 2020-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0005_auto_20200412_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='political_views',
            field=models.CharField(choices=[('democrats', 'The Democratic Party'), ('republicans', 'The Republican Party'), ('no_preference', 'No preference'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Are your political views generally closer to those of', max_length=255, null=True),
        ),
    ]
