# Generated by Django 2.2.9 on 2020-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0005_auto_20200212_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='respondent',
            field=models.CharField(choices=[('Ibrahim', 'Respondent is Ibrahim'), ('Sahr', 'Respondent is Sahr'), ('Sahal', 'Respondent is Sahal'), ('Omar', 'Respondent is Omar'), ('Eman', 'Respondent is Eman'), ('Douglas', 'Respondent is Douglas'), ('Christopher', 'Respondent is Christopher'), ('Philip', 'Respondent is Philip'), ('Theresa', 'Respondent is Theresa'), ('Tracy', 'Respondent is Tracy')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user_bonus',
            field=models.IntegerField(choices=[(2, 'User received a bonus of $2'), (0, 'User received no bonus ($0)')], null=True),
        ),
    ]
