# Generated by Django 2.2.9 on 2020-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0006_auto_20200412_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='approve_of_trump',
            field=models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Do you approve or disapprove of the way Donald Trump is handling his job as president?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='chinese_americans_ventilators',
            field=models.CharField(choices=[('1', 'Never gets a ventilator'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', 'Always gets a ventilator'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Ventilators for Chinese Americans', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cooperate_treatment',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Covid-19 can only be beaten if countries cooperate in finding treatments and a vaccine.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='covid_bioweapon',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Covid-19 was a bioweapon designed by China to wage war on the United States.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='covid_blame',
            field=models.CharField(choices=[('chinese_government', 'The Chinese government'), ('united_states_government', 'The United States government'), ('equally_responsible', 'They are equally responsible'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Who is more to blame for the coronavirus pandemic in the United States?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='economic_outlook',
            field=models.CharField(choices=[('get_better', 'Get better'), ('stay_the_same', 'Stay the same'), ('get_worse', 'Get worse'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Over the next 12 months, do you expect the national economy to get better, get worse, or stay about the same?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='general_trustworthiness',
            field=models.CharField(choices=[('most_people', 'Most people can be trusted'), ('cant_be_too_careful', "Can't be too careful"), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Generally speaking, would you say that most people can be trusted or that you can’t be too careful in dealing with people?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='how_voted',
            field=models.CharField(choices=[('trump', 'Donald Trump'), ('clinton', 'Hillary Clinton'), ('other', 'Other'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Whom did you vote for?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='islamic_extremism',
            field=models.CharField(choices=[('very_concerned', 'Very concerned'), ('somewhat_concerned', 'Somewhat concerned'), ('not_too_concerned', 'Not too concerned'), ('not_concerned', 'Not concerned'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='How concerned are you about the rise of Islamic extremism in the U.S.?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='muslim_americans_ventilators',
            field=models.CharField(choices=[('1', 'Never gets a ventilator'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', 'Always gets a ventilator'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Ventilators for Muslim Americans', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='muslim_coworkers',
            field=models.CharField(choices=[('many', 'Many'), ('some', 'Some'), ('none', 'None at all'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Do you have Muslim co-workers?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='muslims_in_neighborhood',
            field=models.CharField(choices=[('many', 'Many'), ('some', 'Some'), ('none', 'None at all'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Are there Muslims living in your neighborhood?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='non_us_citizens_ventilators',
            field=models.CharField(choices=[('1', 'Never gets a ventilator'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', 'Always gets a ventilator'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Ventilators for non-U.S. citizens', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='over_65_ventilators',
            field=models.CharField(choices=[('1', 'Never gets a ventilator'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', 'Always gets a ventilator'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Ventilators for patients over 65', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='political_views',
            field=models.CharField(choices=[('democrats', 'The Democratic Party'), ('republicans', 'The Republican Party'), ('no_preference', 'No preference'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Are your political views generally closer to those of', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='race_treated_unfairly',
            field=models.CharField(choices=[('often', 'Often'), ('sometimes', 'Sometimes'), ('seldom', 'Seldom'), ('never', 'Never'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Do you think people of your race or ethnicity are treated unfairly?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reducing_terrorism',
            field=models.CharField(choices=[('very_well', 'Very well'), ('fairly_well', 'Fairly well'), ('not_very_well', 'Not very well'), ('not_well_at_all', 'Not well at all'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='In general, how well do you think the American government is doing in reducing the threat of terrorism?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='religion_treated_unfairly',
            field=models.CharField(choices=[('often', 'Often'), ('sometimes', 'Sometimes'), ('seldom', 'Seldom'), ('never', 'Never'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Do you think people of your religion are treated unfairly?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='self_treated_unfairly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Have you, personally, ever been treated unfairly due to your race, ethnicity, or religion?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='share_equipment',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Now that the U.S. has experienced shortages of medical equipment, we should share our masks, ventilators, and other lifesaving equipment with other countries after the virus subsides here.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='us_citizen',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Are you a U.S. citizen?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='voted_last_election',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know_or_refuse', "Don't know/Refuse to answer")], help_text='Did you vote for a presidential candidate in the last election?', max_length=255, null=True),
        ),
    ]
