# Generated by Django 2.2.9 on 2020-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0007_auto_20200212_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='economic_outlook',
            field=models.CharField(choices=[('get_better', 'Get better'), ('stay_the_same', 'Stay the same'), ('get_worse', 'Get worse'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='What about the next 12 months? Do you expect the national economy to get better, get worse, or stay about the same?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='general_trustworthiness',
            field=models.CharField(choices=[('most_people', 'Most people can be trusted'), ('cant_be_too_careful', "Can't be too careful"), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Generally speaking, would you say that most people can be trusted or that you can’t be too careful in dealing with people?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='how_voted',
            field=models.CharField(choices=[('trump', 'Donald Trump'), ('clinton', 'Hillary Clinton'), ('other', 'Other'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Whom did you vote for?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='islamic_extremism',
            field=models.CharField(choices=[('very_concerned', 'Very concerned'), ('somewhat_concerned', 'Somewhat concerned'), ('not_too_concerned', 'Not too concerned'), ('not_concerned', 'Not concerned'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='How concerned are you about the rise of Islamic extremism in the U.S.?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='muslim_coworkers',
            field=models.CharField(choices=[('many', 'Many'), ('some', 'Some'), ('none', 'None at all'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Do you have Muslim co-workers?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='muslims_in_neighborhood',
            field=models.CharField(choices=[('many', 'Many'), ('some', 'Some'), ('none', 'None at all'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Are there Muslims living in your neighborhood?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='news_source',
            field=models.CharField(choices=[('abc_nbc_cbs', 'ABC, NBC, or CBS'), ('cnn', 'CNN'), ('fox_news', 'Fox News'), ('local_tv_radio', 'Local TV or radio'), ('msnbc', 'MSNBC'), ('npr_pbs', 'NPR (National Public Radio) or PBS'), ('newspapers', 'Newspapers, online or in paper'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], help_text='Which do you think is your main source of news?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='political_views',
            field=models.CharField(choices=[('democrats', 'The Democrats'), ('republicans', 'The Republicans'), ('other', 'Other'), ('no_preference', 'No preference'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Are your political views generally closer to...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='race_treated_unfairly',
            field=models.CharField(choices=[('often', 'Often'), ('sometimes', 'Sometimes'), ('seldom', 'Seldom'), ('never', 'Never'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Do you think people of your race or ethnicity are treated unfairly?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reducing_terrorism',
            field=models.CharField(choices=[('very_well', 'Very well'), ('fairly_well', 'Fairly well'), ('not_very_well', 'Not very well'), ('not_well_at_all', 'Not well at all'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='In general, how well do you think the American government is doing in reducing the threat of terrorism?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='religion_treated_unfairly',
            field=models.CharField(choices=[('often', 'Often'), ('sometimes', 'Sometimes'), ('seldom', 'Seldom'), ('never', 'Never'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Do you think people of your religion are treated unfairly?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='self_treated_unfairly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Have you, personally, ever been treated unfairly due to your race, ethnicity, or religion?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='us_citizen',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Are you a U.S. citizen?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='voted_last_election',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't know"), ('refuse_to_answer', 'Refuse to answer')], help_text='Did you vote for a presidential candidate in the last election?', max_length=255, null=True),
        ),
    ]
