# Generated by Django 2.2.9 on 2020-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0007_auto_20200419_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='pid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
