# Generated by Django 2.2.9 on 2020-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_game', '0009_auto_20200525_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='chinese_americans_ventilators',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='muslim_americans_ventilators',
        ),
    ]
