# Generated by Django 2.2.9 on 2020-02-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesuser',
            name='experiment_earning',
        ),
        migrations.RemoveField(
            model_name='gamesuser',
            name='finished_study',
        ),
        migrations.RemoveField(
            model_name='gamesuser',
            name='optout',
        ),
        migrations.RemoveField(
            model_name='gamesuser',
            name='postpone',
        ),
        migrations.RemoveField(
            model_name='gamesuser',
            name='started_study',
        ),
        migrations.RemoveField(
            model_name='gamesuser',
            name='total_earning',
        ),
    ]
